@startuml
left to right direction

actor "HR Advisor" as Employee
rectangle "Database" {
  usecase "Generate Salary Report (All Employees)" as SalaryReportAll
  usecase "Generate Salary Report (Department)" as SalaryReportDepartment
  usecase "Generate Salary Report (My Department)" as SalaryReportMyDepartment
  usecase "Generate Salary Report (Given Role)" as SalaryReportGivenRole
  usecase "Add New Employee" as AddEmployee
  usecase "View Employee Details" as ViewEmployeeDetails
  usecase "Update Employee Details" as UpdateEmployeeDetails
  usecase "Delete Employee Details" as DeleteEmployeeDetails
}

Employee --> SalaryReportAll: Generate Salary Report (All Employees)
Employee --> SalaryReportDepartment: Generate Salary Report (Department)
Employee --> SalaryReportMyDepartment: Generate Salary Report (My Department)
Employee --> SalaryReportGivenRole: Generate Salary Report (Given Role)
Employee --> AddEmployee: Add New Employee
Employee --> ViewEmployeeDetails: View Employee Details
Employee --> UpdateEmployeeDetails: Update Employee Details
Employee --> DeleteEmployeeDetails: Delete Employee Details

@enduml